/* Automatically generated by wasm2c */
#ifndef APP_H_GENERATED_
#define APP_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_0;

typedef struct w2c_app {
  struct w2c_0* w2c_0_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_g;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_app;

void wasm2c_app_instantiate(w2c_app*, struct w2c_0*);
void wasm2c_app_free(w2c_app*);
wasm_rt_func_type_t wasm2c_app_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: '0' '0' */
void w2c_0_0(struct w2c_0*, u32, u32, u32, u32, u32, u32, u32);

/* import: '0' '1' */
void w2c_0_1(struct w2c_0*, u32, u32);

/* import: '0' '10' */
void w2c_0_10(struct w2c_0*, u32);

/* import: '0' '100' */
void w2c_0_100(struct w2c_0*, u32, f64, f64, f64, f64);

/* import: '0' '101' */
f64 w2c_0_101(struct w2c_0*, u32, u32, u32);

/* import: '0' '102' */
void w2c_0_102(struct w2c_0*, u32);

/* import: '0' '103' */
void w2c_0_103(struct w2c_0*, u32, u32, u32, u32, u32, u32);

/* import: '0' '104' */
void w2c_0_104(struct w2c_0*, u32, u32);

/* import: '0' '105' */
u32 w2c_0_105(struct w2c_0*, u32, u32);

/* import: '0' '106' */
void w2c_0_106(struct w2c_0*, u32, u32, u32, u32, u32, u32, u32);

/* import: '0' '107' */
void w2c_0_107(struct w2c_0*, u32, u32);

/* import: '0' '108' */
u32 w2c_0_108(struct w2c_0*);

/* import: '0' '109' */
f64 w2c_0_109(struct w2c_0*);

/* import: '0' '11' */
void w2c_0_11(struct w2c_0*, u32);

/* import: '0' '110' */
u32 w2c_0_110(struct w2c_0*, u32);

/* import: '0' '111' */
void w2c_0_111(struct w2c_0*, u32, u32);

/* import: '0' '112' */
void w2c_0_112(struct w2c_0*, u32, u32);

/* import: '0' '113' */
void w2c_0_113(struct w2c_0*, u32, u32);

/* import: '0' '114' */
void w2c_0_114(struct w2c_0*, u32, u32);

/* import: '0' '115' */
void w2c_0_115(struct w2c_0*, u32, u32);

/* import: '0' '116' */
void w2c_0_116(struct w2c_0*, u32, u32, u32);

/* import: '0' '117' */
u32 w2c_0_117(struct w2c_0*, u32, u32);

/* import: '0' '118' */
u32 w2c_0_118(struct w2c_0*);

/* import: '0' '119' */
void w2c_0_119(struct w2c_0*, u32, u32);

/* import: '0' '12' */
void w2c_0_12(struct w2c_0*, u32, f64, f64, f64, f64, f64);

/* import: '0' '120' */
void w2c_0_120(struct w2c_0*, u32, u32);

/* import: '0' '121' */
void w2c_0_121(struct w2c_0*, u32, f64, f64);

/* import: '0' '122' */
u32 w2c_0_122(struct w2c_0*, u32, u32);

/* import: '0' '123' */
void w2c_0_123(struct w2c_0*, u32);

/* import: '0' '124' */
void w2c_0_124(struct w2c_0*, u32, u32, u32, f64, f64);

/* import: '0' '125' */
void w2c_0_125(struct w2c_0*, u32, u32, u32);

/* import: '0' '126' */
void w2c_0_126(struct w2c_0*, u32, u32);

/* import: '0' '127' */
u32 w2c_0_127(struct w2c_0*, u32);

/* import: '0' '128' */
f64 w2c_0_128(struct w2c_0*, u32, u32);

/* import: '0' '129' */
void w2c_0_129(struct w2c_0*, u32, f64);

/* import: '0' '13' */
u32 w2c_0_13(struct w2c_0*, u32);

/* import: '0' '130' */
void w2c_0_130(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '131' */
void w2c_0_131(struct w2c_0*, u32, u32);

/* import: '0' '132' */
void w2c_0_132(struct w2c_0*, u32);

/* import: '0' '133' */
void w2c_0_133(struct w2c_0*, u32, u32, f64);

/* import: '0' '134' */
u32 w2c_0_134(struct w2c_0*, u32);

/* import: '0' '135' */
void w2c_0_135(struct w2c_0*, u32, u32);

/* import: '0' '136' */
u32 w2c_0_136(struct w2c_0*, u32);

/* import: '0' '137' */
void w2c_0_137(struct w2c_0*, u32);

/* import: '0' '138' */
void w2c_0_138(struct w2c_0*, u32);

/* import: '0' '139' */
void w2c_0_139(struct w2c_0*, u32, u32, f64, f64, f64, f64, f64, f64, f64, f64);

/* import: '0' '14' */
void w2c_0_14(struct w2c_0*, u32, u32, u32, f64, f64);

/* import: '0' '140' */
void w2c_0_140(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '141' */
void w2c_0_141(struct w2c_0*, u32, u32);

/* import: '0' '142' */
void w2c_0_142(struct w2c_0*, u32);

/* import: '0' '143' */
void w2c_0_143(struct w2c_0*, u32);

/* import: '0' '144' */
void w2c_0_144(struct w2c_0*, u32);

/* import: '0' '145' */
void w2c_0_145(struct w2c_0*, u32);

/* import: '0' '146' */
u32 w2c_0_146(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '147' */
void w2c_0_147(struct w2c_0*, u32, u32, u32);

/* import: '0' '148' */
u32 w2c_0_148(struct w2c_0*);

/* import: '0' '149' */
void w2c_0_149(struct w2c_0*, u32, f64, f64, f64, f64);

/* import: '0' '15' */
void w2c_0_15(struct w2c_0*, u32, u32, u32, u32, u32);

/* import: '0' '150' */
void w2c_0_150(struct w2c_0*, u32, u32, u32, u32, u32);

/* import: '0' '151' */
void w2c_0_151(struct w2c_0*, u32);

/* import: '0' '152' */
void w2c_0_152(struct w2c_0*, u32, u32);

/* import: '0' '153' */
f64 w2c_0_153(struct w2c_0*, u32, u32);

/* import: '0' '154' */
void w2c_0_154(struct w2c_0*, u32, u32);

/* import: '0' '155' */
void w2c_0_155(struct w2c_0*, u32, u32);

/* import: '0' '156' */
void w2c_0_156(struct w2c_0*, u32, u32, u32);

/* import: '0' '157' */
u32 w2c_0_157(struct w2c_0*);

/* import: '0' '158' */
f64 w2c_0_158(struct w2c_0*);

/* import: '0' '159' */
void w2c_0_159(struct w2c_0*, u32, u32, u32);

/* import: '0' '16' */
void w2c_0_16(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '160' */
u32 w2c_0_160(struct w2c_0*, u32);

/* import: '0' '161' */
void w2c_0_161(struct w2c_0*, u32, u32);

/* import: '0' '162' */
void w2c_0_162(struct w2c_0*, u32);

/* import: '0' '163' */
u32 w2c_0_163(struct w2c_0*, u32, u32, u32);

/* import: '0' '164' */
void w2c_0_164(struct w2c_0*, u32);

/* import: '0' '165' */
u32 w2c_0_165(struct w2c_0*, u32);

/* import: '0' '166' */
void w2c_0_166(struct w2c_0*, u32, u32, f64, f64, f64, f64, f64, u32, f64, u32, u32, u32);

/* import: '0' '167' */
void w2c_0_167(struct w2c_0*, u32, f64, f64, f64, f64);

/* import: '0' '168' */
void w2c_0_168(struct w2c_0*, u32, f64, f64, f64, f64);

/* import: '0' '169' */
void w2c_0_169(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '17' */
void w2c_0_17(struct w2c_0*, u32, u32, f64);

/* import: '0' '170' */
u32 w2c_0_170(struct w2c_0*);

/* import: '0' '171' */
void w2c_0_171(struct w2c_0*, u32, u32, u32);

/* import: '0' '172' */
void w2c_0_172(struct w2c_0*, u32, u32);

/* import: '0' '173' */
void w2c_0_173(struct w2c_0*, u32, u32);

/* import: '0' '174' */
void w2c_0_174(struct w2c_0*, u32);

/* import: '0' '175' */
void w2c_0_175(struct w2c_0*, u32, u32, u32, u32, u32);

/* import: '0' '176' */
void w2c_0_176(struct w2c_0*, u32);

/* import: '0' '177' */
void w2c_0_177(struct w2c_0*, u32, u32, u32);

/* import: '0' '178' */
u32 w2c_0_178(struct w2c_0*);

/* import: '0' '179' */
u32 w2c_0_179(struct w2c_0*, u32, u32);

/* import: '0' '18' */
void w2c_0_18(struct w2c_0*, u32);

/* import: '0' '180' */
void w2c_0_180(struct w2c_0*, u32, u32, u32);

/* import: '0' '181' */
void w2c_0_181(struct w2c_0*, u32, u32);

/* import: '0' '182' */
void w2c_0_182(struct w2c_0*, u32, u32);

/* import: '0' '183' */
void w2c_0_183(struct w2c_0*, u32, f64);

/* import: '0' '184' */
void w2c_0_184(struct w2c_0*, u32, u32, u32, u32, u32, u32, u32);

/* import: '0' '185' */
void w2c_0_185(struct w2c_0*, u32, u32, u32, u32, u32);

/* import: '0' '186' */
void w2c_0_186(struct w2c_0*, u32, u32);

/* import: '0' '187' */
void w2c_0_187(struct w2c_0*, u32, u32, f32, f32);

/* import: '0' '188' */
void w2c_0_188(struct w2c_0*, u32, u32);

/* import: '0' '189' */
void w2c_0_189(struct w2c_0*, u32, u32, u32);

/* import: '0' '19' */
void w2c_0_19(struct w2c_0*, u32, u32);

/* import: '0' '190' */
void w2c_0_190(struct w2c_0*, u32, f64);

/* import: '0' '191' */
void w2c_0_191(struct w2c_0*, u32, u32);

/* import: '0' '2' */
f64 w2c_0_2(struct w2c_0*);

/* import: '0' '20' */
void w2c_0_20(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '21' */
void w2c_0_21(struct w2c_0*, u32, u32);

/* import: '0' '22' */
u32 w2c_0_22(struct w2c_0*, u32);

/* import: '0' '23' */
u32 w2c_0_23(struct w2c_0*);

/* import: '0' '24' */
f64 w2c_0_24(struct w2c_0*, u32);

/* import: '0' '25' */
void w2c_0_25(struct w2c_0*, u32, u32, f64, f64, f64, f64);

/* import: '0' '26' */
void w2c_0_26(struct w2c_0*, u32);

/* import: '0' '27' */
u32 w2c_0_27(struct w2c_0*, u32);

/* import: '0' '28' */
void w2c_0_28(struct w2c_0*, u32);

/* import: '0' '29' */
void w2c_0_29(struct w2c_0*, u32, f64, f64, f64, f64);

/* import: '0' '3' */
void w2c_0_3(struct w2c_0*, u32, u32, u32);

/* import: '0' '30' */
void w2c_0_30(struct w2c_0*, u32, u32);

/* import: '0' '31' */
void w2c_0_31(struct w2c_0*, u32, u32, u32, u32, u32);

/* import: '0' '32' */
u32 w2c_0_32(struct w2c_0*, u32, u32);

/* import: '0' '33' */
void w2c_0_33(struct w2c_0*, u32, u32, f32, f32, f32);

/* import: '0' '34' */
void w2c_0_34(struct w2c_0*, u32, u32);

/* import: '0' '35' */
void w2c_0_35(struct w2c_0*, u32, u32, f64, f64);

/* import: '0' '36' */
void w2c_0_36(struct w2c_0*, u32, f64, f64);

/* import: '0' '37' */
void w2c_0_37(struct w2c_0*, u32, u32, u32);

/* import: '0' '38' */
void w2c_0_38(struct w2c_0*, u32);

/* import: '0' '39' */
u32 w2c_0_39(struct w2c_0*, u32);

/* import: '0' '4' */
void w2c_0_4(struct w2c_0*, u32);

/* import: '0' '40' */
u32 w2c_0_40(struct w2c_0*, u32);

/* import: '0' '41' */
void w2c_0_41(struct w2c_0*, u32);

/* import: '0' '42' */
void w2c_0_42(struct w2c_0*, u32, f32, f32, f32, f32);

/* import: '0' '43' */
void w2c_0_43(struct w2c_0*, u32, u32);

/* import: '0' '44' */
void w2c_0_44(struct w2c_0*, u32, u32, u32, u32, u32);

/* import: '0' '45' */
u32 w2c_0_45(struct w2c_0*);

/* import: '0' '46' */
void w2c_0_46(struct w2c_0*, u32);

/* import: '0' '47' */
void w2c_0_47(struct w2c_0*, u32, u32, u32, u32, u32);

/* import: '0' '48' */
void w2c_0_48(struct w2c_0*, u32, f64);

/* import: '0' '49' */
u32 w2c_0_49(struct w2c_0*);

/* import: '0' '5' */
u32 w2c_0_5(struct w2c_0*, u32);

/* import: '0' '50' */
void w2c_0_50(struct w2c_0*, u32);

/* import: '0' '51' */
void w2c_0_51(struct w2c_0*, u32, u32, u32, u32, u32);

/* import: '0' '52' */
void w2c_0_52(struct w2c_0*, u32, f64);

/* import: '0' '53' */
void w2c_0_53(struct w2c_0*, u32, u32);

/* import: '0' '54' */
void w2c_0_54(struct w2c_0*, u32, u32);

/* import: '0' '55' */
void w2c_0_55(struct w2c_0*, u32);

/* import: '0' '56' */
void w2c_0_56(struct w2c_0*, u32, u32);

/* import: '0' '57' */
void w2c_0_57(struct w2c_0*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: '0' '58' */
u32 w2c_0_58(struct w2c_0*);

/* import: '0' '59' */
void w2c_0_59(struct w2c_0*, u32, u32);

/* import: '0' '6' */
u32 w2c_0_6(struct w2c_0*);

/* import: '0' '60' */
void w2c_0_60(struct w2c_0*, u32, u32, u32);

/* import: '0' '61' */
u32 w2c_0_61(struct w2c_0*, u32, u32);

/* import: '0' '62' */
void w2c_0_62(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '63' */
u32 w2c_0_63(struct w2c_0*, u32);

/* import: '0' '64' */
void w2c_0_64(struct w2c_0*, u32, u32);

/* import: '0' '65' */
void w2c_0_65(struct w2c_0*, u32, u32, u32);

/* import: '0' '66' */
u32 w2c_0_66(struct w2c_0*);

/* import: '0' '67' */
void w2c_0_67(struct w2c_0*, u32, u32);

/* import: '0' '68' */
void w2c_0_68(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '69' */
f64 w2c_0_69(struct w2c_0*);

/* import: '0' '7' */
void w2c_0_7(struct w2c_0*, u32);

/* import: '0' '70' */
void w2c_0_70(struct w2c_0*, u32, u32);

/* import: '0' '71' */
void w2c_0_71(struct w2c_0*, u32, u32, f64, f64);

/* import: '0' '72' */
void w2c_0_72(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '73' */
void w2c_0_73(struct w2c_0*, u32);

/* import: '0' '74' */
u32 w2c_0_74(struct w2c_0*, u32);

/* import: '0' '75' */
u32 w2c_0_75(struct w2c_0*, u32, u32);

/* import: '0' '76' */
void w2c_0_76(struct w2c_0*, u32);

/* import: '0' '77' */
void w2c_0_77(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '78' */
void w2c_0_78(struct w2c_0*, u32);

/* import: '0' '79' */
void w2c_0_79(struct w2c_0*, u32, u32);

/* import: '0' '8' */
u32 w2c_0_8(struct w2c_0*, u32, u32);

/* import: '0' '80' */
void w2c_0_80(struct w2c_0*, u32, u32, u32);

/* import: '0' '81' */
u32 w2c_0_81(struct w2c_0*, u32);

/* import: '0' '82' */
u32 w2c_0_82(struct w2c_0*, u32, u32, u32, u32, u32);

/* import: '0' '83' */
u32 w2c_0_83(struct w2c_0*, u32);

/* import: '0' '84' */
u32 w2c_0_84(struct w2c_0*);

/* import: '0' '85' */
u32 w2c_0_85(struct w2c_0*, u32);

/* import: '0' '86' */
void w2c_0_86(struct w2c_0*);

/* import: '0' '87' */
void w2c_0_87(struct w2c_0*, u32, u32, f64, f64, f64, f64, f64);

/* import: '0' '88' */
u32 w2c_0_88(struct w2c_0*, u32, u32, u32);

/* import: '0' '89' */
f64 w2c_0_89(struct w2c_0*);

/* import: '0' '9' */
void w2c_0_9(struct w2c_0*, u32, u32, u32);

/* import: '0' '90' */
void w2c_0_90(struct w2c_0*, u32, f64, f64);

/* import: '0' '91' */
void w2c_0_91(struct w2c_0*, u32, u32, u32);

/* import: '0' '92' */
void w2c_0_92(struct w2c_0*, u32, u32, u32);

/* import: '0' '93' */
void w2c_0_93(struct w2c_0*, u32, u32, u32, u32);

/* import: '0' '94' */
void w2c_0_94(struct w2c_0*, u32);

/* import: '0' '95' */
void w2c_0_95(struct w2c_0*, u32, u32, u32);

/* import: '0' '96' */
void w2c_0_96(struct w2c_0*, u32);

/* import: '0' '97' */
void w2c_0_97(struct w2c_0*, u32, u32, u32);

/* import: '0' '98' */
void w2c_0_98(struct w2c_0*, u32, u32, u32);

/* import: '0' '99' */
void w2c_0_99(struct w2c_0*, u32, u32, u32, u32, u32);

/* export: 'a' */
u64 w2c_app_a(w2c_app*);

/* export: 'c' */
void w2c_app_c(w2c_app*);

/* export: 'b' */
void w2c_app_b(w2c_app*);

/* export: 'd' */
u32 w2c_app_d(w2c_app*, u32, u32);

/* export: 'g' */
wasm_rt_memory_t* w2c_app_g(w2c_app* instance);

#ifdef __cplusplus
}
#endif

#endif  /* APP_H_GENERATED_ */
