/* Automatically generated by wasm2c */
#ifndef SOMETHING_H_GENERATED_
#define SOMETHING_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_wasm0x3Ajs0x2Dstring;

typedef struct w2c_something {
  struct w2c_wasm0x3Ajs0x2Dstring* w2c_wasm0x3Ajs0x2Dstring_instance;
} w2c_something;

void wasm2c_something_instantiate(w2c_something*, struct w2c_wasm0x3Ajs0x2Dstring*);
void wasm2c_something_free(w2c_something*);
wasm_rt_func_type_t wasm2c_something_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'wasm:js-string' 'test' */
u32 w2c_wasm0x3Ajs0x2Dstring_test(struct w2c_wasm0x3Ajs0x2Dstring*, wasm_rt_externref_t);

#ifdef __cplusplus
}
#endif

#endif  /* SOMETHING_H_GENERATED_ */
